config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'events#index'

  get 'signup' => 'users#new'

  resources :events do
    resources :registrations, only: %i[new create destroy]
  end

  get 'events/filter/:filter' => 'events#index', as: :filtered_events

  resource :session, only: %i[create destroy]
  get 'signin' => 'sessions#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy
  belongs_to :creator, class_name: 'User'

  scope :past, -> { where('date < ?', Time.now).order('date desc') }
  scope :upcoming, -> { where('date > ?', Time.now).order('date asc') }
  validates :title, :date, presence: true
  validates :description, length: { minimum: 10 }
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :events, foreign_key: :creator_id
  validates :username, presence: true

  def upcoming_events
    registrations.select { |r| r.event.date > Time.now }
  end

  def previous_events
    registrations.select { |r| r.event.date < Time.now }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def require_signin
    redirect_to signin_path, alert: 'Please sign in first!' unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    case params[:filter]
    when 'past'
      @events = Event.past
      @title = 'Past Events'
    else
      @events = Event.upcoming
      @title = 'Upcoming Events'
    end
  end

  def show
    @event = Event.find(params[:id])
    @registrations = @event.registrations
    @registration = current_user.registrations.find_by(event_id: @event.id) if current_user
  end

  def new
    if current_user
      @event = Event.new
    else
      redirect_to signin_path
    end
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    if @event.save
      @event.registrations.create!(user: current_user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :require_signin

  def create
    @event = Event.find(params[:event_id])
    @event.registrations.create!(user: current_user)
    # current_user.registrations.create(event_id: @event.id)

    redirect_to @event
  end

  def destroy
    registration = current_user.registrations.find(params[:id])
    registration.destroy

    event = Event.find(params[:event_id])
    redirect_to event
  end

  private

  def registration_params
    params.require(:registration).permit(:event_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(username: params[:username])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back, #{user.username}!"
    else
      flash.now[:alert] = 'Unregistered User!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to events_url, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @events = @user.events
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.previous_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def registration_button(event, registration)
    if registration
      button_to 'Unregister', event_registration_path(event, registration), method: :delete
    else
      button_to 'Register Now', event_registrations_path(event)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  <%= render "shared/errors", object: event %>

  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>

  <%= f.label :date %>
    <%= f.date_field :date %>

  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<h1><%= @title %></h1>

<% @events.each do |event| %>
  <section class="event">
    <div class="summary">
      <h2>
        <%= link_to event.title, event_path(event) %>
      </h2>
      <h5>
        <%= event.date.strftime("%d %B %Y") %>
      </h3>
      <p>
        <%= truncate(event.description, length: 150, separator: ' ') %>
      </p>
      <p>
        Created by 
        <strong><%= link_to event.creator.username, user_path(event.creator.id) %></strong>,
        <%= time_ago_in_words(event.created_at) %> ago<%= %> 
      </p>

    </div>
  </section>
<% end %>

app/views/events/new.html.erb
<h1>Create a New Event</h1>
<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <div class="details">
    <h1><%= @event.title %></h1>
    <h5>
      <%= @event.date.strftime("%d %B %Y") %>
    </h3>
    <p>
      Created by 
      <strong><%= link_to @event.creator.username, user_path(@event.creator.id) %></strong>,
      <%= time_ago_in_words(@event.created_at) %> ago<%= %> 
    </p>
    <p>
      <%= @event.description %>
    </p>
    <%= registration_button(@event, @registration) %>
    <aside>
      <h2><%= pluralize(@registrations.size, "Attendee") %></h2>
      <ul>
        <% @registrations.each do |r|%>
          <li>
            <%= link_to r.user.username,  user_path(r.user.id)%>
          </li>
        <%end%>
      </ul>
    </aside>
  </div>
</section>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
        Site by
        <%= link_to 'Kyle Law','https://github.com/Kyle-Law' %>
    </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
        <ul class="left">
          <li class="logo">
              <%= link_to image_tag("logo.png"), root_path%>
          </li>
          <li>
            <%= link_to "Upcoming", events_path %>
          </li>
          <li>
            <%= link_to "Past", filtered_events_path(:past) %>
          </li>
        </ul>
        <ul class="right">
          <% if current_user %>
            <li>
              <%= link_to "Add New Event", new_event_path, class: "button" %>
            </li>
            <li>
              <%= link_to current_user.username, current_user %>
            </li>
            <li>
              <%= link_to "Sign Out", session_path, method: :delete,class: "button" %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign In", signin_path, class: "button" %>
            </li>
            <li>
              <%= link_to "Sign Up", signup_path, class: "button" %>
            </li>
          <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>
  
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "username" %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
    <h1><%= @user.username %></h1>
    <h3>Member Since</h3>
    <p>
        <%= @user.created_at.strftime("%B %Y") %>
    </p>
      <% if @events.present? %>
        <h3>Created <%= pluralize(@events.size, "Event") %></h3>
        <% if @events.present? %>
          <div class="created-events">
            <ul>
                <% @events.each do |e| %>
                  <li>
                    <%= link_to e.title, e %>
                  </li>
                <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
      <% if @registrations.present? %>
        <h3>Attending <%= pluralize(@upcoming_events.size, "Event") %></h3>
        <div class="attending-events">
          <ul>
            <% @upcoming_events.each do |r| %>
              <li>
                <%= link_to r.event.title, r.event %>
              </li>
            <% end %>
          </ul>
        </div>
        <h3>Attended <%= pluralize(@prev_events.size, "Event") %></h3>
        <div class="attending-events">
          <ul>
            <% @prev_events.each do |r| %>
              <li>
                <%= link_to r.event.title, r.event %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
</section>